[features]
seeds = false
[programs.localnet]
solana_hodl = "2vcJC7mS5WqnRcxw3rx6EN9JevWz9fGPqZAdMzWVDHrh"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/Users/willsnowdon/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
